### PR TITLE
Minor Update To Security

### PR DESCRIPTION
**Pull request by fpcorso**
I made a few changes in the code. First, the esc_attr is for attributes in html not the html itself.

Next, you put the wp_nonce_field('nonce_check','nonce_field');  into a field. So, one for the delete and one for the edit.

Then, you have a wp_verify_nonce( $_POST['nonce_field'], 'nonce_check') inside each function for the checks. You do not have it in the form itself.

Also, you should use intval for the $quote_id as you need to ensure it is an int. The sanitize_text_field would still allow strings.

Lastly, the current_user_can is best in the main function as you only have to check it once that way. Let me know if you have any questions for these suggestions.

### CODE REVIEW

**Comment by fpcorso** [comment]
I just realized that I had cut off part of my comment. I am not sure if you saw it all so I just updated it here.

**Comment by fpcorso** [comment]
Let me know if you had any questions about this.

**Comment by gamekid88** [comment]
I'm literally looking all of the changes now. lol. I see where you made those changes and I understand them. You sure know how to make the code look good. Very organized. Thank you for doing that for me. I see where you used the current user can function within the top area surrounding that method function. Im not sure what to call that. I don't think we were able to figure out what it was called the other night. It makes sense that it is up there and not around every single function in the file. 

I also notice in the install file that you have the require_once function. That is an interesting addition. I either over looked it or forgot to include that one. Makes sense though. I guess it makes the database upgradable?

**Comment by fpcorso** [comment]
According to the Blame feature, you put the require_once there. You can see the blame feature for that file here: https://github.com/gamekid88/final-quote-plugin/blame/first-branch/quotemachineinstallCSS.php

To see the changes I did in this pull request, you can the Files Changed tab at the top of this pull request. Green are my changes/additions and red are things I removed.

**Comment by gamekid88** [comment]
Ok I took a look at it. I really like that File changed feature. It makes sense when there is a lot of collaboration on a single project you can see what they did to it.

**Pull request merged**
